### ISSUE TITLE
Lack of raw data processing codes

### ISSUE THREAD

**Issue by LYL010-ADELA** [Eric991005/TFSTL#1]
@Eric991005 Can you upload the code of processing the raw data (import_data.csv and export_data.csv)? 
I want to modify the raw data to replicate the code, but I found that the data folder only has the processed .npy and .npz files. Can you upload the code on how to process the raw .csv files?

**Comment by Eric991005** [comment]
Hello! In the latest version I uploaded, not only have I included the original CSV files (i.e., import_new.csv and export_new.csv), but I have also provided the methods for generating input data for the TFSTL model. You can find the relevant scripts and instructions in the `TFSTL_Data_generation_methods` folder. These will help you understand and replicate the data processing procedures necessary for generating the input data required by the model. If you encounter any issues using these scripts or understanding the data processing flow, please feel free to contact me.
